#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

####################
## PRECONFIGURATION
#
USER='root'
PASS=`cat /root/.local.pass.mysql`

MYSQL_BIN='/usr/local/bin/mysql'
MYSQL_CMD="${MYSQL_BIN} -u ${USER} -p${PASS}"

#############
## FUNCTIONS
#
usage() {
  echo "usage: ${0##*/} <command> [<params>]"
  echo ""
  echo "Available commands:"
  echo "  engine"
  echo "  processlist"
  echo ""
  echo "Type '${0##*/} help <command>' for help on a specific command."
}
help() {
  if [ "x$1" != 'x' ]; then
    if [ $1 = 'engine' ]; then
      echo "usage: ${0##*/} $1 [<schema>]"
      echo ""
      echo "engine: Display engine information for specified schema or for all"
      echo "        available schemas if none specified."
    elif [ $1 = 'processlist' ]; then
      echo "usage: ${0##*/} $1 [state|user] [<params>]"
      echo ""
      echo "processlist: Display a list of all processes if no options provided or:"
      echo "             - processes in given state if keyword 'state' is used;"
      echo "               available params: binlog, connect, query, sleep"
      echo "             - processes for given user if keyword 'user' is used."
    fi
  fi
}

engine() {
  if [ "x$1" != 'x' ]; then
    _sql="SELECT TABLE_SCHEMA AS 'SCHEMA',
            TABLE_NAME AS 'TABLE',
            ENGINE AS 'ENGINE'
          FROM information_schema.TABLES
          WHERE TABLE_SCHEMA = '$1'"
  else
    _sql="SELECT TABLE_SCHEMA AS 'SCHEMA',
            ENGINE AS 'ENGINE'
          FROM information_schema.TABLES
          GROUP BY TABLE_SCHEMA"
  fi
  $MYSQL_CMD -e "${_sql}"
}
processlist() {
  if [ "x$1" != 'x' ]; then
    if [ $1 = 'state' ]; then
      if [ "x$2" != 'x' ]; then
        if   [ $2 = 'sleep' ]; then
          _sql="SELECT * FROM information_schema.PROCESSLIST WHERE COMMAND = 'Sleep'"
        elif [ $2 = 'query' ]; then
          _sql="SELECT * FROM information_schema.PROCESSLIST WHERE COMMAND = 'Query'"
        elif [ $2 = 'connect' ]; then
          _sql="SELECT * FROM information_schema.PROCESSLIST WHERE COMMAND = 'Connect'"
        elif [ $2 = 'binlog' ]; then
          _sql="SELECT * FROM information_schema.PROCESSLIST WHERE COMMAND LIKE 'Binlog%'"
        fi
      fi
    elif [ $1 = 'user' ]; then
      _sql="SELECT * FROM information_schema.PROCESSLIST WHERE USER = '$2'"
    fi
    $MYSQL_CMD -e "${_sql}"
  else
    $MYSQL_CMD -e "SHOW processlist"
  fi
}

########
## MAIN
#
[ $# -eq 0 ] && usage && exit 1

case $1 in
  "engine")       engine $2;;
  "help")         help $2;;
  "processlist")  processlist $2 "$3";;
  *)              usage && exit 1;;
esac
