#!/bin/sh


usage() {
	echo "usage: ${0##*/} -j <jail_dir> -b <bin_file>"
}

while getopts "b:j:" optionName; do 
    case "$optionName" in 
        b) BIN="$OPTARG";; 
        j) JDIR="$OPTARG";; 
        *) usage;; 
    esac 
done 

[ -z "$BIN" ] && usage && exit 0
[ -z "$JDIR" ] && usage && exit 0

JDIR=${JDIR%/}
LIBC=$(ls /lib/libc.so.*)
LDDS=$(ldd $BIN | awk '$2~/=>/ {print $3}')
_chrooted_bin=${JDIR}${BIN}
_chrooted_bin_path=${JDIR}${BIN%/*}

copy_lib() {
	_lib=$1
	_dest_dir=${JDIR}${_lib%/*}
	_dest_lib=${JDIR}${_lib}
	if [ ! -f ${_dest_lib} ]; then
		echo -e "\tCopying ${_lib##*/} to ${_dest_dir}"
		mkdir -p ${_dest_dir}
		cp -a $_lib ${_dest_lib}
	else
		echo -e "\t${_dest_lib} exists, not copied"
	fi
}

add_lib() {
	_lib=$1
	copy_lib $_lib
	_ldds=$(ldd $_lib | awk '$2~/=>/ {print $3}')
	for _l in $_ldds; do
		add_lib $_l
	done
}

echo "==> Copying $BIN to $_chrooted_bin"
mkdir -p $_chrooted_bin_path
cp -a $BIN $_chrooted_bin

echo "==> Copying libraries"
copy_lib '/libexec/ld-elf.so.1'
for l in $LDDS; do
	add_lib $l
##	echo "${LIB%/*} -> ${LIB##*/}"
##	DIR=`dirname $LIB`
##	FILE=`basename $LIB`
##	echo "$DIR -> $FILE"
done
	echo "==> Check if we're missing anything (paths relative to ${JDIR})"
	ln $(which ldd) ${JDIR}/ldd
	chroot ${JDIR} ./ldd $BIN
	rm ${JDIR}/ldd
